// ======================================================= //
//                                                         //
//  ASKitTests.h                                           //
//  ASKitTests                                             //
//                                                         //
//  Created by Robert Tully on 03/07/2011.                 //
//                                                         //
// --DESCRIPTION------------------------------------------ //
//                                                         //
//  Auto-generated by Xcode - Main Sen Test file           //
//                                                         //
// --LICENSE---------------------------------------------- //
//                                                         //
//  None (Auto-generated by Apple Xcode 4.2)               //
//                                                         //
// ======================================================= //

#import <SenTestingKit/SenTestingKit.h>
#import <ASKit/ASKit.h>

@interface ASKitLogicTests : SenTestCase {
@private
    
}

@end
