// ======================================================= //
//                                                         //
//  ASKitTests.m                                           //
//  ASKitTests                                             //
//                                                         //
//  Created by Robert Tully on 03/07/2011.                 //
//                                                         //
// --DESCRIPTION------------------------------------------ //
//                                                         //
//  Auto-generated by Xcode - Main Sen Test file           //
//                                                         //
// --LICENSE---------------------------------------------- //
//                                                         //
//  None (Auto-generated by Apple Xcode 4.2)               //
//                                                         //
// ======================================================= //

#import "ASKitLogicTests.h"


@implementation ASKitLogicTests

- (void)setUp
{
    [super setUp];
    
    // Set-up code here.
}

- (void)tearDown
{
    // Tear-down code here.
    
    [super tearDown];
}

//- (void)testExample
//{
//    STFail(@"Unit tests are not implemented yet in ASKitTests");
//}

@end
